name: develop-build-and-test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@route-builders'
          always-auth: true
      - name: install modules
        run: npm i
      - name: build & check npm dist
        run: |
          rm -rf dist *.tsbuildinfo && \
          npm run build && \
          [ -s ./dist/index.js ] && \
          [ -s ./types/index.d.ts ]
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@route-builders'
          always-auth: true
      - name: install modules
        run: npm i
      - name: test
        run: |
          npm run test
